import type { GameEvent } from "../game-data";

// Eventos raros e de uma vez só ligados à cultura/piadas internas de clubes grandes.
// Eles ficam separados dos eventos genéricos para crescerem sem contaminar o motor principal.
export const CLUB_SPECIFIC_EVENTS: GameEvent[] = [
  {
    id: "club-bayern-maromba",
    icon: "◆",
    tag: "BAYERN",
    title: "O Bayern decidiu que você precisa ficar enorme",
    description: "Você entrou normal no centro de treinamento. Três meses depois, suas mangas começaram a pedir socorro.",
    needsClubIds: ["bayern"],
    oneTime: true,
    rareChance: 0.42,
    choices: [
      {
        label: "Aceitar o protocolo alemão",
        hint: "Físico permanente ↑↑↑",
        result: "O departamento físico sorri. Você oficialmente entrou para a tradição dos jogadores inexplicavelmente marombas do Bayern.",
        effect: { physicalBoost: 7, fitness: 14, potential: 1, morale: 4 },
      },
      {
        label: "Treinar só o suficiente",
        hint: "Físico permanente ↑",
        result: "Você escapa do modo fisiculturista, mas ainda sai de Munique mais forte do que entrou.",
        effect: { physicalBoost: 3, fitness: 8, discipline: 3 },
      },
    ],
  },
  {
    id: "club-real-madrid-galactico-package",
    icon: "◇",
    tag: "REAL MADRID",
    title: "O pacote galáctico veio completo demais",
    description: "Na apresentação aparecem a chave de um carro, um terno e uma loira misteriosa no camarote. Ninguém explica se tudo isso fazia parte do contrato.",
    needsClubIds: ["real-madrid"],
    oneTime: true,
    rareChance: 0.44,
    choices: [
      {
        label: "Não fazer perguntas",
        hint: "Moral e fama ↑↑",
        result: "Você aceita que certas tradições do Real Madrid não precisam de documentação.",
        effect: { morale: 12, followers: 180_000, reputation: 5, socialSentiment: 4 },
      },
      {
        label: "Perguntar quem organizou isso",
        hint: "Imagem e liderança ↑",
        result: "Ninguém responde. A coletiva gosta da sua cara de confusão.",
        effect: { leadership: 5, mediaRelation: 6, followers: 70_000 },
      },
    ],
  },
  {
    id: "club-barcelona-dna",
    icon: "✦",
    tag: "BARCELONA",
    title: "O treino virou uma discussão de quarenta minutos sobre um passe de dois metros",
    description: "No fim, todo mundo concorda que o passe estava certo, mas poderia ter sido mais Barcelona.",
    needsClubIds: ["barcelona"],
    oneTime: true,
    rareChance: 0.36,
    choices: [
      {
        label: "Absorver o DNA Barça",
        hint: "OVR e liderança ↑",
        result: "Você começa a enxergar triângulos até na fila do mercado.",
        effect: { ovr: 1, leadership: 5, reputation: 3 },
      },
      {
        label: "Só tocar simples",
        hint: "Disciplina ↑↑",
        result: "O treinador suspira, mas admite que a bola chegou no lugar certo.",
        effect: { discipline: 8, morale: 3 },
      },
    ],
  },
  {
    id: "club-liverpool-anfield",
    icon: "●",
    tag: "LIVERPOOL",
    title: "Anfield cantou seu nome antes de você tocar na bola",
    description: "Por alguns minutos fica difícil lembrar que isso ainda é só um jogo de futebol.",
    needsClubIds: ["liverpool"],
    oneTime: true,
    rareChance: 0.38,
    choices: [
      {
        label: "Comprar a energia da arquibancada",
        hint: "Torcida e moral ↑↑",
        result: "A conexão pega. Seu nome vira parte do barulho do estádio.",
        effect: { fans: 14, morale: 10, leadership: 4 },
      },
      {
        label: "Fingir frieza",
        hint: "Reputação ↑",
        result: "Você tenta agir como se fosse normal. Não é.",
        effect: { reputation: 5, fans: 7 },
      },
    ],
  },
  {
    id: "club-flamengo-three-coaches",
    icon: "↻",
    tag: "FLAMENGO",
    title: "Você chegou ao treino e o treinador era outro",
    description: "O auxiliar garante que está tudo normal. É o terceiro técnico que diz isso no mesmo mês.",
    needsClubIds: ["flamengo"],
    oneTime: true,
    rareChance: 0.4,
    choices: [
      {
        label: "Aprender o nome do novo treinador",
        hint: "Liderança e adaptação ↑",
        result: "Você desenvolve a rara habilidade de entender uma prancheta nova em sete minutos.",
        effect: { leadership: 8, adaptation: 8, discipline: 4 },
      },
      {
        label: "Esperar até amanhã",
        hint: "Moral ↑",
        result: "Decisão sensata. Amanhã talvez já seja outro mesmo.",
        effect: { morale: 9, mediaRelation: -2, fans: 4 },
      },
    ],
  },
  {
    id: "club-psg-fashion-week",
    icon: "◇",
    tag: "PARIS",
    title: "A semana de moda entrou no calendário de treinos",
    description: "Você descobre que em Paris existe um segundo campeonato e ele aparentemente envolve casacos caríssimos.",
    needsClubIds: ["psg"],
    oneTime: true,
    rareChance: 0.36,
    choices: [
      {
        label: "Virar atleta e modelo",
        hint: "Seguidores ↑↑↑ · físico ↓",
        result: "As fotos explodem nas redes. O preparador físico finge que não viu você chegando tarde.",
        effect: { followers: 240_000, reputation: 5, fitness: -5, socialSentiment: 6 },
      },
      {
        label: "Ir embora cedo",
        hint: "Físico e disciplina ↑",
        result: "Você perde a melhor foto da noite e ganha o treino da manhã.",
        effect: { fitness: 8, discipline: 6 },
      },
    ],
  },
  {
    id: "club-man-city-laboratory",
    icon: "⬡",
    tag: "MANCHESTER CITY",
    title: "O treino tem mais setas do que jogadores",
    description: "Um analista apresenta uma animação de oito minutos explicando onde você deve estar quando a bola estiver a 37 metros do gol.",
    needsClubIds: ["man-city"],
    oneTime: true,
    rareChance: 0.36,
    choices: [
      {
        label: "Decorar todas as setas",
        hint: "OVR e disciplina ↑",
        result: "Você finalmente entende por que todo mundo parece saber onde a bola vai estar antes dela chegar.",
        effect: { ovr: 1, discipline: 7, leadership: 3 },
      },
      {
        label: "Jogar bola",
        hint: "Moral e confiança ↑",
        result: "O analista anota alguma coisa. Você decide não perguntar.",
        effect: { morale: 8, reputation: 3 },
      },
    ],
  },
  {
    id: "club-dortmund-yellow-wall",
    icon: "▰",
    tag: "DORTMUND",
    title: "A Muralha Amarela resolveu te adotar",
    description: "Você olha para a arquibancada e percebe que algumas pessoas já estão usando uma camisa com seu nome.",
    needsClubIds: ["dortmund"],
    oneTime: true,
    rareChance: 0.38,
    choices: [
      {
        label: "Ir até a arquibancada depois do jogo",
        hint: "Torcida ↑↑↑",
        result: "A relação deixa de ser profissional e vira pessoal muito rápido.",
        effect: { fans: 16, morale: 9, followers: 65_000 },
      },
      {
        label: "Guardar o momento",
        hint: "Moral e liderança ↑",
        result: "Você não faz discurso. Só fica alguns segundos olhando.",
        effect: { morale: 11, leadership: 5 },
      },
    ],
  },
  {
    id: "club-arsenal-project",
    icon: "↗",
    tag: "ARSENAL",
    title: "Disseram que você faz parte do projeto",
    description: "Ninguém sabe exatamente quando o projeto termina, mas aparentemente agora você é uma peça fundamental dele.",
    needsClubIds: ["arsenal"],
    maxAge: 23,
    oneTime: true,
    rareChance: 0.4,
    choices: [
      {
        label: "Confiar no projeto",
        hint: "Potencial ↑↑",
        result: "Você sai da reunião convencido de que o futuro é logo ali. Provavelmente.",
        effect: { potential: 2, morale: 7, reputation: 2 },
      },
      {
        label: "Perguntar a data de entrega",
        hint: "Liderança ↑",
        result: "A sala fica em silêncio por tempo demais.",
        effect: { leadership: 7, mediaRelation: 3 },
      },
    ],
  },
  {
    id: "club-juventus-one-zero",
    icon: "1",
    tag: "JUVENTUS",
    title: "Você descobriu que 1 a 0 também pode ser uma filosofia de vida",
    description: "O treino termina com uma aula inteira sobre como sofrer absolutamente nada depois de fazer um gol.",
    needsClubIds: ["juventus"],
    oneTime: true,
    rareChance: 0.34,
    choices: [
      {
        label: "Abraçar o 1 a 0",
        hint: "Disciplina e liderança ↑↑",
        result: "Você começa a sentir prazer inexplicável quando o relógio passa dos 87 minutos.",
        effect: { discipline: 9, leadership: 6, morale: 4 },
      },
      {
        label: "Tentar fazer o segundo",
        hint: "Reputação ↑",
        result: "A comissão técnica anota seu nome em algum lugar.",
        effect: { reputation: 4, morale: 6 },
      },
    ],
  },
];
