import type { GameEvent } from "./game-data";

/**
 * Histórias pequenas, específicas e meio absurdas que dão personalidade a uma carreira.
 * São separadas dos dramas esportivos para aparecerem com uma frequência própria.
 */
export const FUTBOBO_MOMENTS: GameEvent[] = [
  { id: "funny-gameplay-channel", icon: "🎮", tag: "IDEIA DO COMPANHEIRO", title: "Seu companheiro quer abrir um canal de gameplay com você", description: "Ele já comprou duas webcams, fez uma vinheta duvidosa e decidiu que o canal vai se chamar Dupla de Área. Só falta você concordar.", minAge: 18, oneTime: true, choices: [
    { label: "Virar dupla fixa toda terça-feira", hint: "Seguidores ↑↑ · moral ↑ · descanso ↓", result: "O primeiro vídeo tem áudio estourado, derrota humilhante e uma química impossível de fabricar. A torcida pede episódio novo toda semana.", effect: { followers: 420_000, socialSentiment: 10, morale: 8, lifeBalance: 5, fitness: -4 } },
    { label: "Aceitar apenas um especial", hint: "47% · viral histórico ou live esquecível", result: "Você topa uma participação única e deixa o algoritmo decidir o resto.", effect: {}, luck: { chance: 47, successText: "Um corte da discussão sobre quem roubou o gol passa de dez milhões de visualizações.", failureText: "A live cai três vezes e o vídeo termina com 814 visualizações, 300 delas do próprio companheiro.", successEffect: { followers: 1_200_000, socialSentiment: 14, money: 3, morale: 9 }, failureEffect: { followers: 8_000, morale: 3, mediaRelation: -1 } } },
    { label: "Recusar antes que ele compre luzes RGB", hint: "Foco ↑ · companheiro decepcionado", result: "Você salva suas noites, mas ele estreia sozinho com um boneco de papelão seu na segunda cadeira.", effect: { fitness: 5, lifeBalance: 3, morale: -1 } },
  ]},
  { id: "funny-sticker-pack", icon: "😬", tag: "GRUPO DO ELENCO", title: "Criaram um pacote de figurinhas só com as suas piores expressões", description: "Cada erro seu no treino agora vira uma figurinha nova no grupo. A mais usada é uma foto em que você parece ter esquecido o próprio nome.", minAge: 18, oneTime: true, choices: [
    { label: "Responder criando figurinhas de todo mundo", hint: "Vestiário ↑↑ · guerra declarada", result: "Em dois dias ninguém consegue conversar no grupo sem usar uma careta de outro companheiro.", effect: { morale: 11, leadership: 3, socialSentiment: 4 } },
    { label: "Transformar a pior delas em camiseta", hint: "Dinheiro ↑ · seguidores ↑", result: "A ironia vira produto oficial e a camiseta esgota antes do clube entender a piada.", effect: { money: 4, followers: 180_000, fans: 7, morale: 5 } },
    { label: "Silenciar o grupo por um mês", hint: "Paz ↑ · integração ↓", result: "Você recupera a tranquilidade, mas descobre os horários do treino sempre por último.", effect: { lifeBalance: 5, adaptation: -4, morale: 2 } },
  ]},
  { id: "funny-barber-crest", icon: "✂", tag: "VISUAL NOVO", title: "O barbeiro desenhou o escudo do clube na sua cabeça sem avisar", description: "Você pediu apenas para tirar dos lados. Quando se olha no espelho, existe um escudo enorme e surpreendentemente detalhado na nuca.", minAge: 17, oneTime: true, choices: [
    { label: "Assumir o corte no próximo jogo", hint: "Torcida ↑↑ · dignidade em risco", result: "A câmera encontra sua nuca no aquecimento e o corte vira o símbolo não oficial daquela temporada.", effect: { fans: 13, followers: 240_000, morale: 5, reputation: 3 } },
    { label: "Pintar por cima com uma cor ainda mais absurda", hint: "Imagem ↑↑ · imprensa confusa", result: "A tentativa de esconder chama dez vezes mais atenção e até o clube posta uma enquete sobre o resultado.", effect: { socialSentiment: 12, followers: 360_000, mediaRelation: 4 } },
    { label: "Raspar tudo antes que alguém veja", hint: "Seguro · confiança no barbeiro ↓", result: "Você chega careca ao treino e se recusa a explicar o motivo.", effect: { morale: 2, lifeBalance: -1 } },
  ]},
  { id: "funny-parrot-celebration", icon: "🦜", tag: "VIRAL IMPROVÁVEL", title: "O papagaio do vizinho aprendeu sua comemoração", description: "Além de gritar seu nome, o bicho abre as asas e imita exatamente os três passos da dança que você fez depois do último gol.", minOvr: 68, oneTime: true, choices: [
    { label: "Gravar um vídeo comemorando com ele", hint: "Seguidores ↑↑↑ · torcida ↑", result: "Humano e papagaio fazem a coreografia juntos. A internet encontra o vídeo antes mesmo do treino acabar.", effect: { followers: 850_000, fans: 12, socialSentiment: 16, morale: 8 } },
    { label: "Levar o papagaio ao CT", hint: "Vestiário ↑ · caos pequeno", result: "Ele interrompe a palestra do técnico repetindo uma crítica que ouviu na televisão. Ninguém consegue manter a seriedade.", effect: { morale: 10, mediaRelation: -2, leadership: 2 } },
    { label: "Deixar o animal viver longe dos holofotes", hint: "Equilíbrio ↑ · sem viral", result: "O vídeo fica apenas no grupo da rua e o papagaio mantém uma carreira mais discreta que a sua.", effect: { lifeBalance: 7, morale: 4 } },
  ]},
  { id: "funny-signature-sandwich", icon: "🥪", tag: "CULINÁRIA LOCAL", title: "A lanchonete do estádio criou um sanduíche com seu nome", description: "Ele leva três carnes, molho verde, batata dentro do pão e uma azeitona representando a bola. O dono garante que cada ingrediente simboliza uma qualidade sua.", minAge: 18, oneTime: true, choices: [
    { label: "Provar ao vivo antes do jogo", hint: "Torcida ↑ · físico em perigo", result: "Você termina o sanduíche sob aplausos. O nutricionista assiste ao vídeo em absoluto silêncio.", effect: { fans: 10, followers: 95_000, morale: 6, fitness: -6 } },
    { label: "Pedir uma versão realmente comestível", hint: "Imagem ↑ · parceria local", result: "A receita nova vira sucesso e parte da renda passa a financiar o futebol de base do bairro.", effect: { charity: 6, reputation: 5, fans: 8, money: 2 } },
    { label: "Autorizar o nome sem experimentar", hint: "Dinheiro ↑ · risco gastronômico", result: "Você recebe sua parte e evita descobrir pessoalmente o que o molho roxo significa.", effect: { money: 4, socialSentiment: -2 } },
  ]},
  { id: "funny-wrong-tattoo", icon: "✎", tag: "TORCEDOR DEDICADO", title: "Um torcedor tatuou seu nome com o número errado", description: "A homenagem ocupa as costas inteiras. Seu nome está perfeito, o escudo também, mas o número é de um reserva que quase nunca joga.", minOvr: 72, oneTime: true, choices: [
    { label: "Pagar para corrigir a tatuagem", hint: "Dinheiro ↓ · torcida ↑↑", result: "A correção fica ótima e o torcedor promete conferir duas vezes antes da próxima homenagem permanente.", effect: { money: -2, fans: 14, reputation: 5, socialSentiment: 8 } },
    { label: "Assinar embaixo do número errado", hint: "Humor ↑ · viral", result: "Você transforma o erro em parte da história. A foto da assinatura circula pelo país inteiro.", effect: { followers: 280_000, fans: 10, morale: 6 } },
    { label: "Dizer que aquele sempre foi seu número secreto", hint: "55% · lenda inventada ou mentira descoberta", result: "Você improvisa uma explicação tão detalhada que quase acredita nela.", effect: {}, luck: { chance: 55, successText: "A história pega e a torcida começa a procurar referências ao número em fotos antigas.", failureText: "Um jornalista encontra uma entrevista sua dizendo que odeia exatamente aquele número.", successEffect: { fans: 9, followers: 160_000, mediaRelation: 3 }, failureEffect: { mediaRelation: -6, socialSentiment: -5, morale: 3 } } },
  ]},
  { id: "funny-grandma-tactics", icon: "☕", tag: "FAMÍLIA NA IMPRENSA", title: "Sua avó deu uma entrevista cobrando o treinador", description: "Na porta de casa, ela explicou a uma rádio que você joga fora de posição, recebe poucos passes e precisa cobrar as faltas. A análise tem quinze minutos.", minAge: 18, oneTime: true, choices: [
    { label: "Dizer que ela entende mais que muito comentarista", hint: "Público ↑ · treinador ↓", result: "A frase vira manchete. Sua avó ganha um quadro semanal e o técnico para de sorrir quando você entra na sala.", effect: { followers: 310_000, fans: 9, mediaRelation: 5, reputation: -3 } },
    { label: "Levá-la para conhecer o treinador", hint: "43% · paz histórica ou nova discussão", result: "Você organiza o encontro mais delicado da temporada.", effect: {}, luck: { chance: 43, successText: "Os dois saem abraçados e ela admite que talvez ele saiba alguma coisa de futebol.", failureText: "Ela leva um caderno com sete mudanças táticas e questiona cada resposta do treinador.", successEffect: { morale: 10, reputation: 5, leadership: 3 }, failureEffect: { reputation: -5, morale: 4, mediaRelation: 5 } } },
    { label: "Pedir para a família não falar mais com a imprensa", hint: "Controle ↑ · avó ofendida", result: "As entrevistas param, mas ela passa a mandar as análises diretamente no seu celular.", effect: { lifeBalance: -3, morale: 3 } },
  ]},
  { id: "funny-lost-boots", icon: "👟", tag: "VESTIÁRIO", title: "Suas chuteiras desapareceram vinte minutos antes do jogo", description: "O roupeiro procura em três malas e só encontra um par da base dois números menor, com o nome de um garoto escrito na lateral.", minAge: 17, oneTime: true, choices: [
    { label: "Jogar com as chuteiras apertadas", hint: "46% · atuação lendária ou pés destruídos", result: "Você amarra o par emprestado e tenta esquecer que não sente os dedos.", effect: {}, luck: { chance: 46, successText: "Você faz sua melhor atuação do mês e o garoto exige as chuteiras de volta exatamente como ficaram.", failureText: "Cada arrancada dói e o departamento médico precisa cuidar dos seus pés por semanas.", successEffect: { reputation: 10, morale: 8, fans: 6 }, failureEffect: { fitness: -14, injuryRisk: 7, morale: -5 } } },
    { label: "Pedir um par usado a um companheiro", hint: "Seguro · história de vestiário", result: "O tamanho serve, mas a chuteira tem o nome dos filhos dele bordado. Você agradece a cada toque na bola.", effect: { morale: 6, leadership: 3, fitness: -2 } },
    { label: "Oferecer recompensa pela mala correta", hint: "Dinheiro ↓ · equipamento recuperado", result: "A mala aparece no ônibus da equipe adversária a quatro minutos do aquecimento.", effect: { money: -1, fitness: 3, morale: 4 } },
  ]},
  { id: "funny-grocery-tactics", icon: "▤", tag: "VAZAMENTO TÁTICO", title: "A câmera flagrou seu papel secreto — era uma lista de compras", description: "A transmissão aproxima a imagem esperando instruções confidenciais. O país inteiro lê: arroz, detergente, banana e ração para gato.", minAge: 18, oneTime: true, choices: [
    { label: "Explicar cada item como código tático", hint: "Imprensa ↑ · criatividade ↑", result: "Você garante que 'banana' significa atacar o espaço entre lateral e zagueiro. Dois programas esportivos analisam a teoria.", effect: { mediaRelation: 9, followers: 170_000, reputation: 3 } },
    { label: "Publicar a receita completa depois do jogo", hint: "Seguidores ↑ · humor", result: "A lista vira conteúdo e milhares de torcedores cozinham a mesma janta naquela noite.", effect: { followers: 260_000, socialSentiment: 12, morale: 5 } },
    { label: "Admitir que esquece tudo sem anotar", hint: "Autenticidade ↑ · aura ↓", result: "A sinceridade aproxima o público, embora seus companheiros passem a esconder suas próprias listas.", effect: { fans: 6, reputation: -1, lifeBalance: 3 } },
  ]},
  { id: "funny-missing-mascot", icon: "◇", tag: "OPERAÇÃO MASCOTE", title: "A pessoa que veste o mascote faltou no evento do clube", description: "Há duzentas crianças esperando, o traje está livre e alguém da comunicação percebe que você tem exatamente a altura necessária.", minAge: 18, maxOvr: 82, oneTime: true, choices: [
    { label: "Vestir o mascote sem contar para ninguém", hint: "Torcida ↑↑ · identidade secreta", result: "Você dança por quarenta minutos, sua no traje e só revela a verdade na foto final.", effect: { fans: 15, morale: 10, charity: 5, fitness: -3 } },
    { label: "Aparecer como jogador e mascote ao mesmo tempo", hint: "Produção ↑ · seguidores ↑", result: "O clube improvisa com um funcionário no traje e encena uma discussão entre vocês. As crianças compram completamente a história.", effect: { followers: 140_000, fans: 10, mediaRelation: 4 } },
    { label: "Encontrar outro voluntário", hint: "Liderança ↑ · seguro", result: "Você convence um zagueiro veterano, que leva o papel muito mais a sério do que todos esperavam.", effect: { leadership: 5, morale: 6 } },
  ]},
  { id: "funny-wedding-celebration", icon: "♪", tag: "FENÔMENO CULTURAL", title: "Sua comemoração virou a dança obrigatória de casamentos", description: "Vídeos mostram noivos, avós e crianças repetindo seu gesto na pista. Um casal pede que você ensine pessoalmente antes da cerimônia.", minOvr: 74, oneTime: true, choices: [
    { label: "Gravar um tutorial oficial", hint: "Seguidores ↑↑ · torcida ↑", result: "O tutorial tem oito passos, nomes próprios e uma dificuldade que você nunca percebeu que existia.", effect: { followers: 620_000, fans: 9, socialSentiment: 13, money: 2 } },
    { label: "Aparecer de surpresa no casamento", hint: "Momento histórico · equilíbrio ↓", result: "Você entra na pista no refrão e cria uma lembrança que aquela família contará por gerações.", effect: { fans: 14, reputation: 7, morale: 9, lifeBalance: -3 } },
    { label: "Aposentar a comemoração imediatamente", hint: "Mistério ↑ · público confuso", result: "Você nunca mais repete o gesto, o que apenas faz a dança ficar ainda mais famosa.", effect: { reputation: 4, socialSentiment: -2 } },
  ]},
  { id: "funny-fantasy-mom", icon: "▦", tag: "FANTASY DO ELENCO", title: "A mãe de um companheiro deixou você no banco no fantasy", description: "Ela lidera a liga interna do elenco e explicou no grupo que seu momento não inspira confiança. O filho dela ainda mandou a captura de tela.", minAge: 18, oneTime: true, choices: [
    { label: "Prometer pontuação só para fazê-la se arrepender", hint: "47% · resposta em campo ou print eterno", result: "Você transforma uma liga de fantasy familiar em motivação esportiva real.", effect: {}, luck: { chance: 47, successText: "Sua temporada explode e ela admite publicamente que foi o pior erro de escalação da rodada.", failureText: "Você passa em branco e o print volta ao grupo depois de cada jogo.", successEffect: { reputation: 10, morale: 11, fans: 5 }, failureEffect: { morale: -7, socialSentiment: -3 } } },
    { label: "Pedir conselhos para a nova rodada", hint: "Humor ↑ · vestiário ↑", result: "Ela envia um áudio de seis minutos explicando por que você deveria passar mais a bola.", effect: { morale: 9, leadership: 2, followers: 40_000 } },
    { label: "Criar seu próprio time e deixá-la fora", hint: "Rivalidade paralela · foco ↓", result: "Nasce um campeonato particular que recebe mais atenção no grupo do que a tabela de verdade.", effect: { morale: 7, lifeBalance: -2, socialSentiment: 4 } },
  ]},
  { id: "funny-button-football-locker", icon: "●", tag: "FUTEBOL DE BOTÃO", title: "O elenco montou um campeonato de futebol de botão na concentração", description: "Cada botão representa um jogador real. O mais estranho: seu companheiro usa você como volante marcador, independentemente da sua posição de verdade.", minAge: 18, oneTime: true, choices: [
    { label: "Exigir jogar controlando seu próprio botão", hint: "Moral ↑ · campeonato sério demais", result: "Você passa a noite treinando peteleco e comemora cada gol de plástico como se valesse título continental.", effect: { morale: 12, lifeBalance: 4, leadership: 2 } },
    { label: "Questionar sua função tática no tabuleiro", hint: "Vestiário ↑ · ego em debate", result: "A discussão termina com três formações desenhadas e ninguém lembrando quem venceu a partida.", effect: { morale: 8, adaptation: 3 } },
    { label: "Mandar fazer botões personalizados do elenco", hint: "Dinheiro ↓ · legado ↑", result: "O presente vira tradição nas viagens e cada novo contratado recebe seu botão antes da estreia.", effect: { money: -2, leadership: 7, reputation: 4 } },
  ]},
  { id: "funny-haunted-hotel", icon: "☾", tag: "CONCENTRAÇÃO", title: "Seu companheiro jura que o hotel da concentração é assombrado", description: "Às três da manhã ele bate na sua porta com travesseiro, mala e um vídeo de uma cortina se mexendo. O ar-condicionado aparece claramente na gravação.", minAge: 18, oneTime: true, choices: [
    { label: "Deixar ele dormir no chão do quarto", hint: "Grupo ↑ · sono ↓", result: "Ele ronca até o amanhecer e agradece por você ter enfrentado o fantasma ao lado dele.", effect: { morale: 7, leadership: 5, fitness: -7 } },
    { label: "Investigar o corredor com uma live", hint: "42% · viral ou bronca do clube", result: "Vocês saem com lanternas, chinelos e nenhuma autorização da comissão.", effect: {}, luck: { chance: 42, successText: "A investigação encontra um funcionário empurrando um carrinho e vira uma das lives mais engraçadas do ano.", failureText: "O alarme de incêndio dispara e o elenco inteiro acorda furioso com vocês.", successEffect: { followers: 480_000, morale: 8, socialSentiment: 11 }, failureEffect: { morale: -6, reputation: -5, fitness: -8 } } },
    { label: "Mostrar que era o ar-condicionado", hint: "Sono ↑ · amizade levemente ferida", result: "A explicação resolve o mistério, mas ele prefere dormir com a luz acesa mesmo assim.", effect: { fitness: 5, morale: 2 } },
  ]},
  { id: "funny-shirt-upside-down", icon: "↕", tag: "ERRO DE UNIFORME", title: "Seu número foi estampado de cabeça para baixo", description: "O uniforme especial chegou minutos antes do jogo. Seu número funciona dos dois lados e ninguém da equipe de material percebeu qual era o certo.", minAge: 18, oneTime: true, choices: [
    { label: "Jogar assim e chamar de edição limitada", hint: "Camisa rara · seguidores ↑", result: "A peça vira instantaneamente a camisa mais procurada da temporada.", effect: { followers: 190_000, fans: 8, money: 3, socialSentiment: 7 } },
    { label: "Corrigir com fita no vestiário", hint: "Seguro · visual questionável", result: "A fita aguenta sete minutos e depois o número parece uma equação incompleta.", effect: { morale: 4, reputation: -1 } },
    { label: "Trocar de número só por aquele jogo", hint: "Superstição nova · surpresa", result: "Você escolhe um número improvável e parte da torcida passa a tratá-lo como amuleto.", effect: { fans: 5, morale: 5 } },
  ]},
  { id: "funny-school-exam", icon: "✎", tag: "EDUCAÇÃO", title: "Seu gol perdido virou questão numa prova de matemática", description: "O enunciado calcula o ângulo que você deveria ter usado para acertar o canto. Um aluno manda a foto e pergunta se a resposta do professor está certa.", minAge: 18, oneTime: true, choices: [
    { label: "Resolver a questão em vídeo", hint: "Seguidores ↑ · risco matemático", result: "Você acerta o ângulo, erra uma divisão básica e conclui que na hora o goleiro parecia maior.", effect: { followers: 210_000, socialSentiment: 10, mediaRelation: 4, morale: 5 } },
    { label: "Visitar a escola e refazer o chute", hint: "Torcida ↑↑ · ação comunitária", result: "A aula termina no pátio, com vinte crianças tentando reproduzir a jogada.", effect: { charity: 7, fans: 11, reputation: 6, lifeBalance: -2 } },
    { label: "Mandar uma resposta: faltou sorte", hint: "Curto · honesto", result: "O professor concede meio ponto pela justificativa e inclui sua resposta no gabarito comentado.", effect: { morale: 4, socialSentiment: 4 } },
  ]},
  { id: "funny-podcast-locker", icon: "●", tag: "PODCAST CLANDESTINO", title: "Dois companheiros começaram um podcast escondido no vestiário", description: "O primeiro episódio se chama Quem Demora Mais no Banho. Seu nome aparece no título, na miniatura e em onze minutos de discussão.", minAge: 19, oneTime: true, choices: [
    { label: "Invadir o segundo episódio para se defender", hint: "Seguidores ↑ · vestiário ↑", result: "Sua defesa dura quarenta minutos e cria outras cinco acusações para o episódio seguinte.", effect: { followers: 330_000, morale: 10, socialSentiment: 8 } },
    { label: "Produzir um direito de resposta profissional", hint: "Imprensa ↑ · piada cresce", result: "A iluminação, os gráficos e a trilha dramática tornam o assunto muito maior do que era.", effect: { mediaRelation: 7, followers: 170_000, morale: 5 } },
    { label: "Confiscar o microfone como veterano", hint: "Liderança ↑ · diversão ↓", result: "O podcast acaba oficialmente e reaparece três dias depois gravado dentro do ônibus.", effect: { leadership: 5, morale: -2 } },
  ]},
  { id: "funny-drone-cake", icon: "◇", tag: "ANIVERSÁRIO", title: "Um drone tentou entregar seu bolo no meio do treino", description: "A surpresa organizada pelos companheiros perde altitude, atravessa o treino tático e pousa o bolo exatamente dentro do círculo central.", minAge: 18, oneTime: true, choices: [
    { label: "Comer a parte que sobreviveu", hint: "Moral ↑↑ · físico ↓", result: "Metade da cobertura tem grama, mas ninguém deixa isso atrapalhar a festa.", effect: { morale: 12, fitness: -3, leadership: 2 } },
    { label: "Transformar o drone em alvo no treino", hint: "Diversão ↑ · equipamento em risco", result: "Cada jogador ganha uma tentativa de acertá-lo. O goleiro vence usando as mãos e abre uma discussão sobre as regras.", effect: { morale: 10, fitness: 3, socialSentiment: 4 } },
    { label: "Pedir outro bolo, entregue por uma pessoa", hint: "Dinheiro ↓ · festa garantida", result: "A segunda tentativa chega inteira e sem invadir nenhuma atividade tática.", effect: { money: -1, morale: 8, lifeBalance: 3 } },
  ]},
  { id: "funny-autograph-opponent", icon: "✦", tag: "RESPEITO INESPERADO", title: "Um adversário pediu seu autógrafo no intervalo", description: "Ele esperou o túnel esvaziar, tirou uma caneta da meia e explicou que o irmão mais novo é seu maior fã.", minOvr: 80, oneTime: true, choices: [
    { label: "Assinar e mandar uma mensagem para o irmão", hint: "Respeito ↑↑ · momento humano", result: "A rivalidade volta no segundo tempo, mas aquela família guarda uma história muito maior que o placar.", effect: { reputation: 8, fans: 9, rivalRespect: 7, morale: 5 } },
    { label: "Trocar as camisas depois do jogo", hint: "Respeito ↑ · torcida dividida", result: "Vocês cumprem o combinado e a imagem da troca vira assunto entre as duas torcidas.", effect: { rivalRespect: 9, reputation: 5, fans: -2 } },
    { label: "Dizer para ele pedir só depois da partida", hint: "Foco ↑ · respeito", result: "Ele entende, joga os noventa minutos no limite e aparece com a mesma caneta após o apito.", effect: { fitness: 3, rivalRespect: 5, leadership: 3 } },
  ]},
  { id: "funny-superstition-socks", icon: "▥", tag: "SUPERSTIÇÃO", title: "O roupeiro descobriu que você usa uma meia do avesso há meses", description: "A sequência boa começou no mesmo dia do engano. Agora ninguém no clube quer ser responsável por virar a meia para o lado certo.", minAge: 18, oneTime: true, choices: [
    { label: "Transformar a meia em ritual oficial", hint: "Moral ↑ · superstição permanente", result: "O roupeiro guarda a peça separada e confirma três vezes o lado antes de cada jogo.", effect: { morale: 9, titleBoost: 3, lifeBalance: -2 } },
    { label: "Lavar, virar e encerrar a história", hint: "Razão ↑ · vestiário apreensivo", result: "Nada imediatamente ruim acontece, mas todos observam seu primeiro toque no jogo seguinte.", effect: { leadership: 4, morale: 2 } },
    { label: "Leiloar a meia para caridade", hint: "Caridade ↑↑ · sorte em jogo", result: "A peça arrecada um valor absurdo e você precisa encontrar um novo amuleto antes da rodada.", effect: { charity: 12, reputation: 7, fans: 7, titleBoost: -2 } },
  ]},
  { id: "funny-bus-wrong-stadium", icon: "↗", tag: "LOGÍSTICA", title: "O ônibus seguiu a torcida errada e chegou a outro estádio", description: "O motorista viu dezenas de camisas parecidas, entrou no comboio e só percebeu o erro diante de um jogo regional a quarenta quilômetros do destino.", minAge: 18, oneTime: true, choices: [
    { label: "Descer e cumprimentar a torcida surpresa", hint: "Torcida ↑ · atraso ↑", result: "O pequeno estádio recebe uma visita inesquecível, enquanto a comissão calcula cada minuto perdido.", effect: { fans: 10, reputation: 5, fitness: -5 } },
    { label: "Organizar o aquecimento dentro do ônibus", hint: "Liderança ↑ · adaptação ↑", result: "Alongamento no corredor e ativação sentado: você impede o grupo de chegar completamente frio.", effect: { leadership: 7, adaptation: 5, fitness: -2 } },
    { label: "Fingir que era uma ação planejada", hint: "52% · marketing genial ou mentira óbvia", result: "A assessoria tenta transformar o erro de rota em visita comunitária surpresa.", effect: {}, luck: { chance: 52, successText: "A versão convence, rende uma campanha bonita e ninguém menciona o GPS.", failureText: "O motorista dá uma entrevista contando tudo e desmonta a história em vinte segundos.", successEffect: { mediaRelation: 7, fans: 8, reputation: 4 }, failureEffect: { mediaRelation: -7, reputation: -3, morale: 5 } } },
  ]},
  { id: "funny-commentator-name", icon: "🎙", tag: "NARRAÇÃO", title: "O narrador passou a temporada inteira pronunciando seu nome errado", description: "A versão dele já ficou tão famosa que parte da torcida acha que você é quem fala o próprio sobrenome errado.", minAge: 18, oneTime: true, choices: [
    { label: "Ensinar ao vivo com muita paciência", hint: "Imprensa ↑ · identidade recuperada", result: "Ele acerta no ensaio, erra novamente no jogo e pede desculpas durante a comemoração do gol.", effect: { mediaRelation: 8, followers: 80_000, morale: 4 } },
    { label: "Adotar a pronúncia como apelido", hint: "Torcida ↑↑ · nome novo", result: "O erro vira canto de arquibancada, faixa e estampa de camiseta.", effect: { fans: 12, followers: 190_000, money: 2, reputation: 3 } },
    { label: "Começar a pronunciar o nome dele errado também", hint: "Humor ↑ · rivalidade amistosa", result: "A brincadeira dura meses e termina com os dois incapazes de lembrar como tudo começou.", effect: { socialSentiment: 10, morale: 7, mediaRelation: 3 } },
  ]},
];
